/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BLACKJACK_H_RPCGEN
#define _BLACKJACK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct card {
	int rank;
	int suit;
	int point;
};
typedef struct card card;

#define BLACKJACK 0x20000001
#define BLACKJACK_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define initialize 0
extern  int * initialize_1(void *, CLIENT *);
extern  int * initialize_1_svc(void *, struct svc_req *);
#define draw_for_player 1
extern  card * draw_for_player_1(void *, CLIENT *);
extern  card * draw_for_player_1_svc(void *, struct svc_req *);
#define dealer_before_turn 2
extern  card * dealer_before_turn_1(void *, CLIENT *);
extern  card * dealer_before_turn_1_svc(void *, struct svc_req *);
#define dealer_turn 3
extern  char ** dealer_turn_1(void *, CLIENT *);
extern  char ** dealer_turn_1_svc(void *, struct svc_req *);
#define check_win 4
extern  char ** check_win_1(void *, CLIENT *);
extern  char ** check_win_1_svc(void *, struct svc_req *);
#define show_hole_card 5
extern  char ** show_hole_card_1(void *, CLIENT *);
extern  char ** show_hole_card_1_svc(void *, struct svc_req *);
#define get_player_points 6
extern  int * get_player_points_1(void *, CLIENT *);
extern  int * get_player_points_1_svc(void *, struct svc_req *);
#define get_dealer_points 7
extern  int * get_dealer_points_1(void *, CLIENT *);
extern  int * get_dealer_points_1_svc(void *, struct svc_req *);
#define player_choice 8
extern  int * player_choice_1(int *, CLIENT *);
extern  int * player_choice_1_svc(int *, struct svc_req *);
extern int blackjack_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define initialize 0
extern  int * initialize_1();
extern  int * initialize_1_svc();
#define draw_for_player 1
extern  card * draw_for_player_1();
extern  card * draw_for_player_1_svc();
#define dealer_before_turn 2
extern  card * dealer_before_turn_1();
extern  card * dealer_before_turn_1_svc();
#define dealer_turn 3
extern  char ** dealer_turn_1();
extern  char ** dealer_turn_1_svc();
#define check_win 4
extern  char ** check_win_1();
extern  char ** check_win_1_svc();
#define show_hole_card 5
extern  char ** show_hole_card_1();
extern  char ** show_hole_card_1_svc();
#define get_player_points 6
extern  int * get_player_points_1();
extern  int * get_player_points_1_svc();
#define get_dealer_points 7
extern  int * get_dealer_points_1();
extern  int * get_dealer_points_1_svc();
#define player_choice 8
extern  int * player_choice_1();
extern  int * player_choice_1_svc();
extern int blackjack_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_card (XDR *, card*);

#else /* K&R C */
extern bool_t xdr_card ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BLACKJACK_H_RPCGEN */
