/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "blackjack.h"

bool_t
xdr_card (XDR *xdrs, card *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->rank))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->suit))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->point))
		 return FALSE;
	return TRUE;
}
